import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F5F8FF] antialiased`}>
        <header className='w-[100%] flex justify-around flex-row mt-5'>
          <div>
            <h1 className='text-black font-sans text-[40px] font-medium'>
              FasterUI
            </h1>
          </div>
          <div className='w-[500px] bg-white rounded-md text-[#8987A1] font-medium font-sans flex justify-around'>
            <button>
              <Link href='/'>Home</Link>
            </button>
            <button>
              <Link href='/About'>About</Link>
            </button>
            <button>
              <Link href='/HowItWorks'>How it Works</Link>
            </button>
            <button>
              <Link href='/Servicee'>Services</Link>
            </button>
          </div>
          <div>
            <button className='mr-5 text-[#adadaf] bg-[#fafafa] w-[58px] border-solid '>
              <Link href='/SignIn'>Sign in</Link>
            </button>
            <button className='w-[132px] h-[48px] bg-[#4E47FF] rounded-lg font-bold '>
              <Link href='/SignUp'>Sign up</Link>
            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
